# Generated by Django 3.0.7 on 2020-07-18 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20200717_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='timespan',
            field=models.TextField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='imgSrc',
            field=models.CharField(max_length=50),
        ),
    ]
