# Generated by Django 3.0.7 on 2020-07-18 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20200719_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='imgSrc',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='timespan',
            field=models.CharField(max_length=50),
        ),
    ]
