# Generated by Django 3.0.7 on 2020-07-31 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20200719_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='article',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='award',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='demoSrc',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='keywords',
            field=models.CharField(default='Game, Roguelike', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='teamSize',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.CharField(default='Typescript, React', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='imgSrc',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='project',
            name='pretext',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
