# Generated by Django 3.0.7 on 2020-08-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20200731_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='links',
            field=models.CharField(default='', max_length=240),
            preserve_default=False,
        ),
    ]
