# Generated by Django 3.0.7 on 2020-08-01 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_project_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='imgSrc',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='project',
            name='pretext',
            field=models.CharField(max_length=400),
        ),
    ]
